spring:  
  profiles: runtime
  application:    
    name: online-sla
  datasource:    
    url: jdbc:sqlserver://${DB_IP};databaseName=${DB_SCHEMA};sendTimeAsDateTime=false    
    schema-username: ${DB_SCHEMA}    
    username: ${DB_USER}    
    password: ${DB_PASS}    
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver  
  jpa:    
    database-platform: org.hibernate.dialect.SQLServer2012Dialect    
    show-sql: false
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    default-property-inclusion: NON_NULL
server:  
  port: 8080
---
spring:  
  profiles: local
  application:    
    name: online-sla
  h2:
    console: true
    path: /h2
  datasource:    
    url: jdbc:h2:file:/home/filipe/dbh2local
    schema-username: ${DB_SCHEMA} 
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:    
    database-platform: org.hibernate.dialect.H2Dialect   
#    show-sql: true
    format_sql: true
    use_sql_comments: true
    type: true
    hibernate:
      ddl-auto: none
      format_sql: true
      use_sql_comments: true
      type: true
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    default-property-inclusion: NON_NULL
#logging:
#  level:
#    org:
#      hibernate:
#        type: trace
server:  
  port: 8081
  